# Introduction {-}

This template is intended for e-book style Notes of various topics, conferences, and miscellaneous collections. 

This section contain all prior information that we need to know before we start this book.

I also use this section to store miscellaneous resource that I may need before I do my serious edit.


<hr>

**Format 1 e-Book:**

**Kia ora my friend,**

Welcome to my online textbook on XXX

This textbook is intended to provide a comprehensive introduction to 

The book is written for three audiences: (1) (2) (3) 

Readers are assumed to be familiar with 

For the first Chapter.. For the second chapter... Lastly we .... in Chapter X.

Most of the information discussed in this book should have been referenced, also, at the end of each chapter a list of “further reading” will be provided for more advanced or detailed treatment of the subject. 

If you have found a typo or have any questions about contents in this book, feel free to contact me through my email jxue533@aucklanduni.ac.nz . 

Lastly please Note, this is a work in progress, the print version of the book are not yet available.


**From New Zealand with TimTam and Love!**

**Jung Xue**

**Latest date of editing: "`r Sys.Date()`"**
 
 



<hr>

To cite from this book, please use the following:

```
Xue, J.H. (year) "title", 1st edition,  RBookDown: Auckland, New Zealand. Unpublished.  <github site> . Accessed on <current date>.

```

<hr>



**Format 2 Conference:**

- **Time:** xx:00pm/xx/xx/xx 
- **Venue:** The university of Auckland 303S-310 [Map]()
- **Registartion:** xx/xx/xx  
- **Hosted by:** [Host association website]()

**Keynote Speakers:**

| Speaker      |topic         | Email        | Website      |
|:-------------|:-------------|:-------------|:-------------|
| Joe Smith    |Pickles       | xx@gmail.com | [Uni](www.google.com)  |
|   |   |   |   |
|   |   |   |   |

**interesting I have meet/noticed**

| People       |Field/Job     | Contact      | Facts        |
|:-------------|:-------------|:-------------|:-------------|
| Joe Smith    | Consultant @ UoA  | xx@gmail.com | His from New Caledonia |
|   |   |   |   |
|   |   |   |   |

Note: All information disclosed within this conference e-note are intented for personal use. 



